### ISSUE TITLE
Issue with Submission

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/hw3-haridave0718#1]
Hi haridave0718,

I don't see any interpretation of your results in the HW assignment. This is explicitly in the rubric and would amount to 30 missed points. You have until Wednesday, Nov 08, 11:59pm to add these result interpretations, or you will receive no greater than 70/100 on this portion of the overall assignment.

**Comment by haridave0718** [comment]
I have added a new updated .ipynb file and .html file with the interpretations added as well. Apologies for missing that during the initial submission.
Really appreciate you providing extra time for making the changes.

Regards
